[project]
name = "mcp-aggregator"
version = "0.1.0"
description = "MCP Aggregator - Multi-server MCP proxy for integration and aggregation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.11.3",
]

[project.scripts]
uv-mcp-aggregator = "mcp_aggregator:main"
