server:
  port: ${PORT:8080}

spring:
  application:
    name: mcp-java
  cloud:
    discovery:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Policy Guard Configuration
policy:
  guard:
    url: ${POLICY_GUARD_URL:http://mcp-policy-guard:8090}

# OpenTelemetry Configuration
otel:
  service:
    name: ${OTEL_SERVICE_NAME:mcp-java}
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://aspire-dashboard:18889}

# Logging Configuration
logging:
  level:
    com.aspire.mcp: DEBUG
    org.springframework.web: INFO
    io.opentelemetry: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
