apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: ai-core
  name: ai-core
spec:
  ports:
  - name: http
    port: 3002
    targetPort: 0
  - name: tcp
    port: 8000
    targetPort: 0
  selector:
    app: ai-core
  type: ClusterIP