apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: chat
  name: chat
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: chat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: chat
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: chat
        image: '{{ .Values.images.chat }}'
        imagePullPolicy: Always
        name: chat
        ports:
        - containerPort: 8001
          name: http
      imagePullSecrets:
      - name: image-pull-secret
      terminationGracePeriodSeconds: 180