apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: chat
  name: chat
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 0
  selector:
    app: chat
  type: ClusterIP