apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: guard
  name: guard
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: guard
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: guard
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: guard
        image: '{{ .Values.images.guard }}'
        imagePullPolicy: Always
        name: guard
        ports:
        - containerPort: 7000
          name: http
      imagePullSecrets:
      - name: image-pull-secret
      terminationGracePeriodSeconds: 180