apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: guard
  name: guard
spec:
  ports:
  - name: http
    port: 7000
    targetPort: 0
  selector:
    app: guard
  type: ClusterIP