apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mcp-policy-guard
  name: mcp-policy-guard
spec:
  ports:
  - name: http
    port: 8090
    targetPort: 0
  selector:
    app: mcp-policy-guard
  type: ClusterIP