apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mcp-aggregator
  name: mcp-aggregator
spec:
  ports:
  - name: http
    port: 7000
    targetPort: 0
  selector:
    app: mcp-aggregator
  type: ClusterIP