apiVersion: v1
kind: Service
metadata:
  name: mcp-policy-guard
  labels:
    app: mcp-policy-guard
  annotations: {}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8090
    targetPort: 8090
  selector:
    app: mcp-policy-guard
