[project]
name = "guard"
version = "0.1.0"
description = "An empty gaurd - as McP proxy for integration placeholder"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.11.3",
]

[project.scripts]
uv-guard = "guard:main"
